app: order-system
stage: dev
component: postgresql
name: order-system-db

inputs:
  region: ${env:REGION}
  zone: ${env:ZONE}
  dBInstanceName: ${name}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:order-system-vpc.vpcId}
    subnetId: ${output:${stage}:${app}:order-system-vpc.subnetId}
  extranetAccess: true
