app: order-system
stage: dev
component: express
name: order-system-server

inputs:
  src: ./
  region: ${env:REGION}
  functionName: ${name}
  functionConf:
    runtime: Nodejs12.16
    timeout: 900
    environment:
      variables:
        DB_HOST: ${output:${stage}:${app}:${app}-db.public.host}
        DB_PORT: ${output:${stage}:${app}:${app}-db.public.port}
        DB_USER: ${output:${stage}:${app}:${app}-db.public.user}
        DB_PASSWORD: ${output:${stage}:${app}:${app}-db.public.password}
        DB_NAME: ${output:${stage}:${app}:${app}-db.public.dbname}
        WS_BACK_URL: ${output:${stage}:${app}:${app}-ws.apigw.wsBackUrl}
  apigatewayConf:
    environment: release
    protocols:
      - http
      - https
