app: order-system
stage: dev
component: websocket
name: order-system-ws

inputs:
  src: ./
  region: ${env:REGION}
  faas:
    name: ${name}
    runtime: Nodejs12.16
    timeout: 900
    environment:
      variables:
        DB_HOST: ${output:${stage}:${app}:order-system-db.public.host}
        DB_PORT: ${output:${stage}:${app}:order-system-db.public.port}
        DB_USER: ${output:${stage}:${app}:order-system-db.public.user}
        DB_PASSWORD: ${output:${stage}:${app}:order-system-db.public.password}
        DB_NAME: ${output:${stage}:${app}:order-system-db.public.dbname}
  apigw:
    environment: release
    protocols:
      - http
      - https
